### ISSUE TITLE
Install failed when add sharpcaster SharpCaster 0.3.4 lib

### ISSUE THREAD

**Issue by mohamedhelmypoweraspect** [Tapanila/SharpCaster#86] opened 2017-01-15 08:30 UTC
Install failed when add sharpcaster SharpCaster 0.3.4 lib from https://www.nuget.org/packages/SharpCaster/
Install failed. Rolling back...
Package 'protobuf-net-sharpcaster.2.0.0.668' does not exist in project 'ios project'
Could not install package 'protobuf-net-sharpcaster 2.0.0.668'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mohamedhelmypoweraspect** [comment] 2017-01-15 14:40
Could not install package 'protobuf-net-sharpcaster 2.0.0.668'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Tapanila** [comment] 2017-01-16 07:24
Could you send me the iOS project to teemu(at)tapanila.net so I can take a look at it.
Protobuf-net-sharpcaster is targetting Profile 151 so it should work with ios

**Comment by mohamedhelmypoweraspect** [comment] 2017-01-16 09:17
I sent the project 
Thanks in advance

**Comment by Tapanila** [comment] 2017-01-26 15:30
Thanks for the project.
Still looking into issue and having problems understanding why it doesn't work.

According to this page it should work:
http://danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2/

But I can now reproduce the issue so working on it.

**Comment by TomCouser** [comment] 2017-03-05 13:18
Is there any update with this issue? Currently facing the same problem. Thanks for spending the time to look into this.

**Comment by Tapanila** [comment] 2017-03-06 11:15
It seems to be a problem on nuget itself. Only way to fix it seems to be change the nuget packages. Waiting for the VS 2017 launch before I do changes since there might be some other stuff that I need to change now.

Will have some kind of solution to this problem on upcoming weekend.

**Comment by Tapanila** [comment] 2017-04-02 17:56
Was not able to fix this yet. Building PCL + targetting multiple platforms is pretty hard :(

Currently looking into .net standard which would fix this

**Comment by Tapanila** [comment] 2017-05-21 18:34
This should be fixed from xamarin side. If this still an issue please reopen with a sample project that can reproduce the issue

**Closed by Tapanila** 2017-05-21 18:34 UTC
